


export const metadata = {
  title: "Advanced React",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >Contact page mei aapka swagat hai {children}</body>
    </html>
  );
}
